// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PemesananMakanan.Data;

#nullable disable

namespace PemesananMakanan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231107010654_PesanDanPesanan3")]
    partial class PesanDanPesanan3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("PemesananMakanan.Models.Makanan", b =>
                {
                    b.Property<int>("MakananId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Harga")
                        .HasColumnType("REAL");

                    b.Property<string>("MakananNama")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PicturePath")
                        .HasColumnType("TEXT");

                    b.HasKey("MakananId");

                    b.ToTable("Makanans");

                    b.HasData(
                        new
                        {
                            MakananId = 1,
                            Harga = 5000f,
                            MakananNama = "Indomie",
                            PicturePath = "/images/indomie.jpg"
                        },
                        new
                        {
                            MakananId = 2,
                            Harga = 3000f,
                            MakananNama = "Telor Ceplok",
                            PicturePath = "/images/telorCeplok.jpg"
                        });
                });

            modelBuilder.Entity("PemesananMakanan.Models.Pesan", b =>
                {
                    b.Property<int>("PesanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MakananId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("pesananId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PesanId");

                    b.HasIndex("MakananId");

                    b.HasIndex("pesananId");

                    b.ToTable("Pesans");
                });

            modelBuilder.Entity("PemesananMakanan.Models.Pesanan", b =>
                {
                    b.Property<int>("pesananId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotalHarga")
                        .HasColumnType("REAL");

                    b.HasKey("pesananId");

                    b.ToTable("Pesanans");
                });

            modelBuilder.Entity("PemesananMakanan.Models.Pesan", b =>
                {
                    b.HasOne("PemesananMakanan.Models.Makanan", "Makanan")
                        .WithMany()
                        .HasForeignKey("MakananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PemesananMakanan.Models.Pesanan", null)
                        .WithMany("Pesans")
                        .HasForeignKey("pesananId");

                    b.Navigation("Makanan");
                });

            modelBuilder.Entity("PemesananMakanan.Models.Pesanan", b =>
                {
                    b.Navigation("Pesans");
                });
#pragma warning restore 612, 618
        }
    }
}
