// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PemesananMakanan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231011010851_FirstDb")]
    partial class FirstDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PemesananMakanan.Models.Makanan", b =>
                {
                    b.Property<int>("MakananId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakananId"));

                    b.Property<float>("Harga")
                        .HasColumnType("real");

                    b.Property<string>("MakananNama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakananId");

                    b.ToTable("Makanans");
                });

            modelBuilder.Entity("PemesananMakanan.Models.Pesanan", b =>
                {
                    b.Property<int>("PesananId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PesananId"));

                    b.Property<int>("MakananId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("TotalHarga")
                        .HasColumnType("real");

                    b.HasKey("PesananId");

                    b.HasIndex("MakananId");

                    b.ToTable("Pesanans");
                });

            modelBuilder.Entity("PemesananMakanan.Models.Pesanan", b =>
                {
                    b.HasOne("PemesananMakanan.Models.Makanan", "Makanan")
                        .WithMany()
                        .HasForeignKey("MakananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makanan");
                });
#pragma warning restore 612, 618
        }
    }
}
